### ISSUE TITLE
p5 demo link in readme returns 404

### ISSUE THREAD

**Issue by lisajamhoury** [LingDong-/handpose-facemesh-demos#3]
Thanks for this great repo. So many excellent examples! 

I noticed this link to the p5 editor is broken. Do you have an updated link? 

`Also available on editor.p5js.org: https://editor.p5js.org/LingDong-/sketches/ef6FB-uNq`

Thanks again.

**Comment by LingDong-** [comment]
Links fixed: b3d42a9a595dde3be9a93229a383bf5fc60f8d8e (broken link was due to editor.p5js.org merging my accounts)

Thanks!

**Comment by lisajamhoury** [comment]
Oh great. Thank you!
