### ISSUE TITLE
Uncaught (in promise) TypeError: n.kernel_impls.nonMaxSuppressionV3Impl is not a function

### ISSUE THREAD

**Issue by lisajamhoury** [LingDong-/handpose-facemesh-demos#4]
Thanks for these great examples! 

I'm getting the following error when I try to run all of the facemesh examples on glitch. 

```
Uncaught (in promise) TypeError: n.kernel_impls.nonMaxSuppressionV3Impl is not a function
    at Object.kernelFunc (tfjs-backend-webgl:17)
    at f (engine.ts:562)
    at engine.ts:619
    at t.scopedRun (engine.ts:436)
    at t.runKernelFunc (engine.ts:616)
    at nonMaxSuppression_ (non_max_suppression.ts:41)
    at Object.nonMaxSuppression (operation.ts:45)
    at h.getBoundingBoxes (facemesh:17)
    at t.<anonymous> (facemesh:17)
    at facemesh:17
```

I'm pretty sure I ran these about a month ago without any issues. Maybe a recent change is causing this bug?

**Comment by LingDong-** [comment]
Hi @lisajamhoury , thanks for reporting the issue!
I'm pretty sure it's because tfjs is making breaking changes to their library (again). Probably can be fixed by specifying the exact tfjs version number in the cdn links... I'll look into it!

**Comment by LingDong-** [comment]
Hi @lisajamhoury 

These issues are now fixed in the demos by explicitly setting the tfjs versions (latest ones as of today):

```html
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core@2.4.0/dist/tf-core.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-webgl@2.4.0"></script>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-converter@2.4.0/dist/tf-converter.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow-models/facemesh@0.0.4"></script>

```

Thanks!

**Comment by lisajamhoury** [comment]
Awesome! Thanks so much @LingDong-
